import { randomUUID } from "crypto";

import {
  DeleteObjectCommand,
  ListObjectsV2Command,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { logger } from "firebase-functions";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { defineSecret } from "firebase-functions/params";

import { DEFAULT_REGION } from "./schema";

/**
 * R2 API token for raices-care-images.
 *
 * Set both with `firebase functions:secrets:set` and paste the value at the
 * prompt. They never reach the Flutter client. The client receives a
 * short-lived PUT URL, then uploads the JPEG itself.
 */
const R2_ACCESS_KEY_ID = defineSecret("R2_ACCESS_KEY_ID");
const R2_SECRET_ACCESS_KEY = defineSecret("R2_SECRET_ACCESS_KEY");

const R2_ENDPOINT =
  "https://6cd4a37d293aa36c028b11945b8c74e1.r2.cloudflarestorage.com";
const R2_BUCKET = "raices-care-images";

/** Matches the ceiling the old Storage rules enforced. */
const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

/** Long enough to finish a JPEG upload, short enough to limit a leaked URL. */
const UPLOAD_URL_SECONDS = 5 * 60;

/**
 * A replaced avatar uses a fixed key. This keeps the custom domain from
 * serving the previous file for long after an overwrite.
 */
const CACHE_CONTROL = "public, max-age=300";

const JPEG = "image/jpeg";

/** Plant ids are generated by the app. Reject anything that could escape the prefix. */
const PLANT_ID = /^[A-Za-z0-9_-]{1,128}$/;

const ENFORCE_APP_CHECK = false;
const PUBLIC_INVOKER = "public";

export const imageSecrets = [R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY];

/**
 * Removes every object under `users/{uid}/`, including the avatar and plant
 * photos. Used when the account itself is deleted.
 */
export async function deleteUserImages(uid: string): Promise<number> {
  const client = r2Client();
  const prefix = `users/${uid}/`;
  let removed = 0;
  let token: string | undefined;
  do {
    const page = await client.send(
      new ListObjectsV2Command({
        Bucket: R2_BUCKET,
        Prefix: prefix,
        ContinuationToken: token,
      }),
    );
    for (const item of page.Contents ?? []) {
      if (!item.Key?.startsWith(prefix)) {
        continue;
      }
      await client.send(
        new DeleteObjectCommand({ Bucket: R2_BUCKET, Key: item.Key }),
      );
      removed += 1;
    }
    token = page.IsTruncated ? page.NextContinuationToken : undefined;
  } while (token);
  return removed;
}

function r2Client(): S3Client {
  return new S3Client({
    region: "auto",
    endpoint: R2_ENDPOINT,
    credentials: {
      accessKeyId: R2_ACCESS_KEY_ID.value(),
      secretAccessKey: R2_SECRET_ACCESS_KEY.value(),
    },
    // The SDK's default checksum headers are not part of the URL the app
    // signs, and R2 rejects the upload when they are required.
    requestChecksumCalculation: "WHEN_REQUIRED",
    responseChecksumValidation: "WHEN_REQUIRED",
  });
}

function requireUser(uid: string | undefined): string {
  if (!uid) {
    throw new HttpsError("unauthenticated", "Sign in to continue.");
  }
  return uid;
}

function requireJpeg(contentType: unknown): void {
  if (contentType !== JPEG) {
    throw new HttpsError("invalid-argument", "Only images can be uploaded.");
  }
}

function requireLength(contentLength: unknown): number {
  if (
    typeof contentLength !== "number" ||
    !Number.isInteger(contentLength) ||
    contentLength < 1
  ) {
    throw new HttpsError("invalid-argument", "That photo could not be saved.");
  }
  if (contentLength > MAX_UPLOAD_BYTES) {
    throw new HttpsError(
      "invalid-argument",
      "That image is larger than the 10 MB limit.",
    );
  }
  return contentLength;
}

function avatarKey(uid: string): string {
  return `users/${uid}/profile/avatar.jpg`;
}

function plantKey(uid: string, plantId: unknown): {
  photoId: string;
  storagePath: string;
} {
  if (typeof plantId !== "string" || !PLANT_ID.test(plantId)) {
    throw new HttpsError("invalid-argument", "That photo could not be saved.");
  }
  const photoId = randomUUID();
  return {
    photoId,
    storagePath: `users/${uid}/plants/${plantId}/${photoId}.jpg`,
  };
}

/** A key the caller may delete: their own folder, and nothing that climbs out of it. */
function ownedKey(uid: string, storagePath: unknown): string {
  if (typeof storagePath !== "string" || storagePath.length > 1500) {
    throw new HttpsError("invalid-argument", "That photo could not be saved.");
  }
  const prefix = `users/${uid}/`;
  if (
    !storagePath.startsWith(prefix) ||
    storagePath.includes("..") ||
    storagePath.includes("\\") ||
    storagePath.includes("//")
  ) {
    throw new HttpsError("permission-denied", "You do not have access to that.");
  }
  return storagePath;
}

/**
 * Builds the object key and a PUT URL for one JPEG.
 *
 * The key is chosen here. The client cannot name an object outside its folder.
 */
export const prepareImageUpload = onCall(
  {
    region: DEFAULT_REGION,
    secrets: imageSecrets,
    enforceAppCheck: ENFORCE_APP_CHECK,
    invoker: PUBLIC_INVOKER,
  },
  async (request) => {
    const uid = requireUser(request.auth?.uid);
    const data = request.data as {
      kind?: unknown;
      plantId?: unknown;
      contentType?: unknown;
      contentLength?: unknown;
    };

    requireJpeg(data.contentType);
    const contentLength = requireLength(data.contentLength);

    const stored =
      data.kind === "avatar"
        ? { storagePath: avatarKey(uid), photoId: undefined }
        : data.kind === "plant"
          ? plantKey(uid, data.plantId)
          : null;
    if (stored == null) {
      throw new HttpsError("invalid-argument", "That photo could not be saved.");
    }

    try {
      const uploadUrl = await getSignedUrl(
        r2Client(),
        new PutObjectCommand({
          Bucket: R2_BUCKET,
          Key: stored.storagePath,
          ContentType: JPEG,
          ContentLength: contentLength,
          CacheControl: CACHE_CONTROL,
        }),
        { expiresIn: UPLOAD_URL_SECONDS },
      );
      return {
        storagePath: stored.storagePath,
        uploadUrl,
        photoId: stored.photoId ?? null,
      };
    } catch (error) {
      logger.error("Could not sign an image upload", error);
      throw new HttpsError("internal", "That photo could not be saved.");
    }
  },
);

/**
 * Deletes one object. The key must sit under the caller's own folder.
 */
export const deleteImage = onCall(
  {
    region: DEFAULT_REGION,
    secrets: imageSecrets,
    enforceAppCheck: ENFORCE_APP_CHECK,
    invoker: PUBLIC_INVOKER,
  },
  async (request) => {
    const uid = requireUser(request.auth?.uid);
    const storagePath = ownedKey(
      uid,
      (request.data as { storagePath?: unknown }).storagePath,
    );

    try {
      await r2Client().send(
        new DeleteObjectCommand({ Bucket: R2_BUCKET, Key: storagePath }),
      );
      return { storagePath };
    } catch (error) {
      logger.error("Could not delete an image", error);
      throw new HttpsError("internal", "That photo could not be removed.");
    }
  },
);
